"""empty message

Revision ID: 958b37e152a4
Revises: a324361c327d
Create Date: 2018-05-24 14:33:20.060532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '958b37e152a4'
down_revision = 'a324361c327d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_url', sa.Column('created_by_', sa.String(), nullable=False))
    op.add_column('short_url', sa.Column('modified_by_', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('short_url', 'modified_by_')
    op.drop_column('short_url', 'created_by_')
    # ### end Alembic commands ###
